# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sidedish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sidedish
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SidedishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SidedishUITests' do
    # Pods for testing
  end

end
